import { NextRequest, NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { getSessionContext } from '@/lib/supabase/server'
import { can } from '@/lib/auth/rbac'

/**
 * Sign in as another account.
 *
 * Superadmin only — a reseller must never be able to assume one of their own
 * users, because that would let a tenant admin read content the tenancy model
 * says is the user's alone.
 *
 * Implemented with a magic link generated by the admin API rather than by
 * forging a token: Supabase issues a genuine session, so the impersonated
 * session expires and can be revoked like any other. Every use is audited
 * before the link is handed back.
 */

export async function POST(request: NextRequest) {
  const session = await getSessionContext()

  if (!session) {
    return NextResponse.json({ error: 'Not signed in' }, { status: 401 })
  }

  // Deliberately narrower than a role check: only this permission grants it,
  // and only superadmin holds it.
  if (!can(session.role, 'users.impersonate')) {
    return NextResponse.json(
      { error: 'Only a superadmin can sign in as another account.' },
      { status: 403 }
    )
  }

  const body = await request.json().catch(() => null)

  if (!body?.id) {
    return NextResponse.json({ error: 'id is required' }, { status: 400 })
  }

  if (body.id === session.userId) {
    return NextResponse.json({ error: 'That is already your account.' }, { status: 400 })
  }

  const { data: target } = await supabaseAdmin
    .from('profiles')
    .select('id, email, role, status')
    .eq('id', body.id)
    .maybeSingle()

  if (!target) {
    return NextResponse.json({ error: 'Account not found' }, { status: 404 })
  }

  if (target.role === 'superadmin') {
    return NextResponse.json(
      { error: 'Cannot sign in as another superadmin.' },
      { status: 403 }
    )
  }

  if (target.status === 'suspended') {
    return NextResponse.json(
      { error: 'That account is suspended. Reactivate it first.' },
      { status: 409 }
    )
  }

  // Audit before issuing, so a link is never handed out unrecorded.
  await supabaseAdmin.from('audit_logs').insert({
    actor_id: session.userId,
    actor_role: session.role,
    tenant_id: session.tenantId,
    action: 'account.impersonate',
    target_type: 'profile',
    target_id: target.id,
    metadata: { email: target.email, role: target.role },
    ip_address: request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || null,
    user_agent: request.headers.get('user-agent'),
  })

  const { data, error } = await supabaseAdmin.auth.admin.generateLink({
    type: 'magiclink',
    email: target.email as string,
  })

  if (error || !data?.properties?.action_link) {
    return NextResponse.json(
      { error: error?.message ?? 'Could not create a sign-in link.' },
      { status: 400 }
    )
  }

  return NextResponse.json({
    ok: true,
    email: target.email,
    // Opening this link replaces the current session with the target's.
    link: data.properties.action_link,
  })
}

export const dynamic = 'force-dynamic'
